### ISSUE TITLE
有关数据集的处理

### ISSUE THREAD

**Issue by youxin01** [InsaneOnion/ConCLR#1]
大佬好，我最近也在准备复现这篇文章，但是对于数据集处理存在问题，在Synthtext数据集当中，一个图片可能会很复杂，没有论文当中提到的那么简单，那么在拼接的时候，是需要对图片先进行切割成小块字符串吗？
![Uploading 屏幕截图 2024-07-01 203037.jpg…]()

**Comment by InsaneOnion** [comment]
一个图片可能会很复杂是指什么呢？我的处理方法是直接拼接后resize,实现效果有在readme中贴出。

**Comment by InsaneOnion** [comment]
您贴出的截图没有正常显示呢

**Comment by InsaneOnion** [comment]
hh，这只是数据集的展示封面吧？事实上数据集中的图片就是下图中那样的

**Comment by InsaneOnion** [comment]
抱歉，刚刚的回答有些问题，确实是需要对原始数据集做crop处理才能得到论文中的数据集，可见https://github.com/FangShancheng/ABINet/blob/main/tools/crop_by_word_bb_syn90k.py，或者直接下载https://github.com/FangShancheng/ABINet仓库中提供的lmdb数据集。

**Comment by SuperGGB0** [comment]
哦！我看40G没有直接下，原来是这样，谢谢您了。

**Comment by SuperGGB0** [comment]
hh，我刚刚也是找到了ABINet的数据集，谢谢！

**Comment by InsaneOnion** [comment]
不用谢~有其他问题也欢迎讨论~
