### ISSUE TITLE
有关数据集标签

### ISSUE THREAD

**Issue by youxin01** [InsaneOnion/ConCLR#2]
大佬好，我在加载数据集的时候，读取mbd文件后打印出来key和value，如下：

![image](https://github.com/InsaneOnion/ConCLR/assets/131187530/6ae62c88-d2c0-44bf-8ba0-51ec9d44a085)

我的疑惑在于为什么没有label，数据集下载的是ABINet的ST
https://github.com/FangShancheng/ABINet

**Comment by InsaneOnion** [comment]
你的代码没有截全，你应该只是读取了lmdb中的图片，该lmdb数据集中的image与label并不是键值对的关系，他们是分开存储的。比如image的key为"image-{idx}"，label为"label-{idx}"。（btw,我们是不是在做同一个老师的考核

**Comment by SuperGGB0** [comment]
原来是这样，这么巧吗？Zhouyu老师吗？

**Comment by InsaneOnion** [comment]
😃hh是的

**Comment by SuperGGB0** [comment]
hhh，你好厉害，感觉稳的😁

**Comment by InsaneOnion** [comment]
hh过奖了，我也是小白，大家都很优秀，加油。
